### ISSUE TITLE
Please add support for symfony4

### ISSUE THREAD

**Issue by klemens-u** [MWSimple/SCDatetimepickerBundle#2]
That would be great!

**Comment by gonzaloalonsod** [comment]
clone master branch https://github.com/MWSimple/SCDatetimepickerBundle.git in folder vendor

**Comment by gonzaloalonsod** [comment]
@klemens-u 
https://github.com/MWSimple/SCDatetimepickerBundle/commit/8fc37fa3e94c6cfa3bf62820adb0080c0c492d97
